export const SERVICES = [
  {
    id: 'seminar-writing',
    title: 'Seminar Writing',
    description: 'Comprehensive research and documentation for academic seminars, tailored to your specific department and topic.',
    icon: 'BookOpen',
  },
  {
    id: 'project-writing',
    title: 'Project Writing',
    description: 'End-to-end support for final year project writing, including data analysis, literature review, and conclusion.',
    icon: 'FileText',
  },
  {
    id: 'proposal-development',
    title: 'Proposal Development',
    description: 'Crafting persuasive and research-backed academic proposals for projects and research grants.',
    icon: 'PenTool',
  },
  {
    id: 'report-writing',
    title: 'Report Writing',
    description: 'Professional academic report writing for internships, lab work, and field studies.',
    icon: 'BarChart',
  },
  {
    id: 'academic-consultation',
    title: 'Academic Consultation',
    description: 'One-on-one guidance on topic selection, research methodology, and academic navigation.',
    icon: 'MessageSquare',
  },
];

export const PORTFOLIO = [
  {
    id: 1,
    title: 'Blockchain-Powered Academic Reward System',
    category: 'Blockchain / EdTech',
    abstract: 'This research presents a novel framework for incentivizing academic excellence through blockchain technology. By implementing a decentralized reward system at AE-FUNAI, the study demonstrates how tokenized rewards can significantly enhance student engagement in both curricular and extra-curricular activities. The system leverages smart contracts to ensure transparency and immutability in reward distribution, providing a verifiable track record of academic achievement.',
    date: 'April 2024',
  },
  {
    id: 2,
    title: 'AI-Driven Skill Matching & Task Optimization',
    category: 'AI / Human Resources',
    abstract: 'This project develops an AI-based system designed to optimize employee task assignment through intelligent skill matching in remote work environments. By utilizing machine learning algorithms to analyze historical performance data and real-time skill gaps, the system ensures that every task is assigned to the most qualified individual, thereby maximizing organizational productivity and employee satisfaction in distributed teams.',
    date: 'March 2024',
  },
  {
    id: 3,
    title: 'Indoor Air Quality Assessment in Healthcare',
    category: 'Environmental Health',
    abstract: 'A comprehensive comparative research study analyzing pollutant levels and ventilation efficiency in tertiary hospital environments in Ebonyi State. The research evaluates various indoor air quality indicators (IAQ) and their impact on patient recovery times and staff health. Findings provide actionable recommendations for optimizing ventilation systems to mitigate the spread of airborne pathogens in clinical settings.',
    date: 'February 2024',
  },
  {
    id: 4,
    title: 'ML-Based Mental Health Detection System',
    category: 'Health Tech / AI',
    abstract: 'A sophisticated diagnostic tool leveraging natural language processing (NLP) and behavioral patterns to identify early signs of mental health distress. By analyzing linguistic markers in digital communication, the system provides a non-invasive screening method for depression and anxiety, enabling early intervention and personalized support strategies for students and young professionals.',
    date: 'January 2024',
  },
  {
    id: 5,
    title: 'Construction Delay Impact Analysis',
    category: 'Engineering / Economics',
    abstract: 'An in-depth investigation into the cost implications and systemic causes of project delays within the Nigerian construction sector, with a specific focus on the AE-FUNAI development phase. The study identifies key bottlenecks—from procurement issues to logistical hurdles—and proposes a strategic mitigation framework to ensure timely project delivery and budget adherence in future infrastructure works.',
    date: 'December 2023',
  },
  {
    id: 6,
    title: 'AIS Impact on Corporate Profitability',
    category: 'Accounting / Finance',
    abstract: 'This quantitative research analyzes the correlation between modernized Accounting Information Systems (AIS) and bottom-line corporate profitability. By evaluating data from multiple industry sectors, the study demonstrates how real-time financial reporting and automated ledger management reduce operational overhead and improve decision-making accuracy, leading to a statistically significant increase in ROI.',
    date: 'November 2023',
  },
  {
    id: 7,
    title: 'Smart Home Automation (Microcontroller)',
    category: 'Hardware / IoT',
    abstract: 'A full-scale engineering project focusing on the design and implementation of an integrated smart home system. Utilizing microcontroller-based architecture, the project enables remote monitoring and control of lighting, climate, and security systems. The system prioritizes energy efficiency and user-centric interface design, providing a scalable solution for modern residential automation.',
    date: 'October 2023',
  },
  {
    id: 8,
    title: 'Web-Based Crime Reporting & Monitoring',
    category: 'Cybersecurity / Web',
    abstract: 'A digital platform designed to improve community safety and policing through real-time incident reporting. The system features an intuitive web interface for citizens to report crimes and a centralized dashboard for law enforcement to monitor trends and deploy resources effectively. The project emphasizes data security and anonymity for whistleblowers in the Nigerian context.',
    date: 'September 2023',
  },
  {
    id: 9,
    title: 'Nutritional Analysis of Accelerated Food Prep',
    category: 'Food Science / Biochemistry',
    abstract: 'This biochemical study performs a comparative assessment of vitamin compositions in staple foods (specifically Fufu) prepared with chemical accelerants versus traditional methods. The research highlights the nutritional degradation associated with rapid-processing chemicals and advocates for safer, nutrition-focused food processing standards in commercial markets.',
    date: 'August 2023',
  },
  {
    id: 10,
    title: 'Real-time Crop Disease Monitoring',
    category: 'AgriTech / IoT',
    abstract: 'An IoT-driven solution for the early detection of agricultural pests and diseases. By deploying a network of soil and atmospheric sensors, the system provides farmers with real-time data on environmental stressors. Predictive modeling allows for early intervention, significantly reducing crop loss and the need for broad-spectrum chemical pesticides.',
    date: 'July 2023',
  },
  {
    id: 11,
    title: 'Intelligent AC Occupancy Control',
    category: 'IoT / Smart Systems',
    abstract: 'This hardware-based project implements an automated air-conditioning control system utilizing PIR occupancy sensors. Designed for large halls and lecture theaters, the system optimizes power consumption by automatically adjusting cooling based on real-time room usage. The implementation results show a substantial reduction in energy waste without compromising occupant comfort.',
    date: 'June 2023',
  },
  {
    id: 12,
    title: 'Blockchain Student Verification System',
    category: 'Cybersecurity / Blockchain',
    abstract: 'Addressing the global challenge of credential fraud, this project implements a blockchain-based verification system for academic documents. By storing cryptographic hashes of certificates on a decentralized ledger, the system allows employers and institutions to verify student credentials instantly and securely, eliminating the need for slow, manual authentication processes.',
    date: 'May 2023',
  },
  {
    id: 13,
    title: 'The Evolution of HCI',
    category: 'Computer Science / Research',
    abstract: 'A comprehensive academic review tracing the evolution of Human-Computer Interaction from command-line interfaces to modern immersive technologies. The paper explores the shift from machine-centric to user-centric design philosophies and discusses the future of neural-link interfaces and voice-activated ambient computing in personal and professional spheres.',
    date: 'April 2023',
  },
  {
    id: 14,
    title: 'Stock Market Economic Analysis',
    category: 'Economics / Finance',
    abstract: 'This research evaluates the impact of macroeconomic indicators—including inflation, GDP growth, and exchange rates—on stock market performance. Through rigorous statistical analysis of historical data, the study identifies the primary economic drivers of market volatility and provides predictive insights for investors navigating emerging market economies.',
    date: 'March 2023',
  },
  {
    id: 15,
    title: 'Industrial Training (IT) Technical Report',
    category: 'Technical Writing',
    abstract: 'A detailed technical report documenting professional experience gained during a six-month industrial training placement. The report covers project management, technical troubleshooting, and organizational workflows, providing a comprehensive record of skill acquisition and professional development in a real-world engineering environment.',
    date: 'February 2023',
  },
  {
    id: 16,
    title: 'Research Instrument & Questionnaire Design',
    category: 'Research Methodology',
    abstract: 'This project focuses on the development and validation of survey instruments for quantitative research. It covers the methodology behind creating unbiased, statistically relevant questions and the process of pilot testing instruments to ensure data reliability and validity in social science and behavioral studies.',
    date: 'January 2023',
  },
  {
    id: 17,
    title: 'Robotics in Modern Healthcare',
    category: 'Medical Tech / Robotics',
    abstract: 'An exploratory seminar on the transformative role of robotics in contemporary medicine. The research covers surgical robots, assistive exoskeletons for rehabilitation, and autonomous pharmacy systems. It discusses both the technical advancements in precision and the ethical implications of automation in critical patient care.',
    date: 'December 2022',
  },
  {
    id: 18,
    title: 'Advanced Academic Seminar Research',
    category: 'General Research',
    abstract: 'A multidisciplinary seminar paper presenting research on the intersection of emerging technologies and societal structures. The work synthesizes findings from various fields to discuss how digital transformation is reshaping traditional institutional workflows and social interactions in the 21st century.',
    date: 'November 2022',
  },
  {
    id: 19,
    title: 'Anti-Duplication Project Allocation System',
    category: 'Software Engineering',
    abstract: 'This software solution automates the process of academic project topic allocation while monitoring for duplication. By implementing a plagiarism-check algorithm for titles and abstracts, the system ensures that every student project is unique, promoting academic originality and maintaining high institutional research standards.',
    date: 'October 2022',
  },
  {
    id: 20,
    title: 'Automated Student Advisory Chatbot',
    category: 'AI / NLP',
    abstract: 'Developing an intelligent student advisor using Natural Language Processing. This chatbot system provides 24/7 guidance on course selection, graduation requirements, and career planning. By automating routine advisory tasks, the system allows human academic counselors to focus on more complex student needs while improving overall institutional responsiveness.',
    date: 'September 2022',
  },
  {
    id: 21,
    title: 'Musical Chord Progression Engineering',
    category: 'Music Theory / Algorithms',
    abstract: 'An innovative research project exploring the algorithmic design of harmonic musical chord progressions. The study bridges the gap between music theory and software engineering, implementing systems that can automatically generate aesthetically pleasing harmonic structures based on predefined emotional and technical parameters.',
    date: 'August 2022',
  },
  {
    id: 22,
    title: 'Academic Field Trip Report',
    category: 'Experimental Research',
    abstract: 'A systematic field report documenting empirical observations and data collection from a practical academic excursion. The work analyzes real-world environmental and industrial processes, providing a critical comparison between theoretical classroom models and the complexities of on-site implementation.',
    date: 'July 2022',
  },
  {
    id: 23,
    title: 'Academic Research Proposal Sample',
    category: 'Academic Writing',
    abstract: 'A model research proposal designed to serve as a benchmark for academic project applications. The sample demonstrates the effective articulation of research problems, methodology, and expected outcomes, providing a blueprint for students to secure institutional approval and research funding.',
    date: 'June 2022',
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Chidi Okafor',
    role: 'Final Year Student',
    text: 'ScholarBridge helped me navigate my project with ease. The consultation session was a game changer for my research methodology.',
  },
  {
    id: 2,
    name: 'Sarah Adekomi',
    role: 'Master\'s Student',
    text: 'Excellent service! My proposal was accepted on the first attempt thanks to the professional guidance provided here.',
  },
];

export const CONTACT_INFO = {
  email: 'hello@scholarbridge.site',
  whatsapp: '+2347012009012',
  address: 'Ebonyi State, Nigeria',
  socials: {
    linkedin: 'scholarbridge',
    twitter: 'scholarbridge',
  },
};
